# frozen_string_literal: true

module Verdify
  # Mechanically proves that a pull request's diff is confined to the
  # centrally-rendered agent-fleet CI/CD contract: the sentinel-delimited
  # span inside AGENTS.md/CLAUDE.md, the generated .agent-fleet/ci.yaml, and
  # the regenerated MANIFEST.sha256 -- and nothing else.
  #
  # This is the sole evidence a `verdify:fleet-contract-sync` labelled pull
  # request is judged against instead of the full lane-contract/critic
  # chain (jvallery/agents#3577, #3044). A pull request that carries the
  # label but changes anything outside this set, edits anything outside the
  # sentinel span, deletes a managed file, or duplicates/reorders/drops a
  # sentinel fails this check -- it is never silently downgraded to a
  # weaker contract. This check says nothing about what the render is
  # allowed to put *inside* the sentinel span (that remains
  # jvallery/agents's central-render responsibility); it only bounds
  # *where* a labelled pull request may write.
  class ManagedContractDiff
    SENTINEL_BEGIN = "<!-- BEGIN agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
    SENTINEL_END = "<!-- END agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
    SENTINEL_GUARDED_FILES = %w[AGENTS.md CLAUDE.md].freeze
    GENERATED_FILES = %w[.agent-fleet/ci.yaml].freeze
    MANIFEST_FILE = "MANIFEST.sha256"
    GENERATED_FILE_HEADER = /\A# GENERATED by jvallery\/agents\b/.freeze
    ALLOWED_PATHS = (SENTINEL_GUARDED_FILES + GENERATED_FILES + [MANIFEST_FILE]).freeze

    Result = Struct.new(:errors) do
      def confined?
        errors.empty?
      end
    end

    def self.evaluate(repo:, base_sha:, head_sha:)
      new(repo: repo, base_sha: base_sha, head_sha: head_sha).evaluate
    end

    def initialize(repo:, base_sha:, head_sha:)
      @repo = repo
      @base_sha = base_sha
      @head_sha = head_sha
    end

    def evaluate
      errors = []
      changes = changed_paths
      if changes.empty?
        errors << "no changed paths to confirm as a managed contract sync"
        return Result.new(errors)
      end

      renamed = changes.select { |fields| fields.first.to_s.start_with?("R", "C") }
      if renamed.any?
        described = renamed.map { |fields| fields.drop(1).join(" -> ") }.sort.join(", ")
        errors << "renamed or copied paths are not permitted in a managed contract sync: #{described}"
      end

      ordinary = changes.reject { |fields| fields.first.to_s.start_with?("R", "C") }
      paths = ordinary.map { |fields| fields[1] }

      out_of_scope = paths - ALLOWED_PATHS
      errors << "changed paths outside the managed contract: #{out_of_scope.sort.join(', ')}" if out_of_scope.any?

      deleted = ordinary.select { |fields| fields.first == "D" }.map { |fields| fields[1] }
      errors << "managed contract paths must not be deleted: #{deleted.sort.join(', ')}" if deleted.any?

      SENTINEL_GUARDED_FILES.each do |path|
        next unless paths.include?(path)

        errors.concat(sentinel_confinement_errors(path))
      end

      GENERATED_FILES.each do |path|
        next unless paths.include?(path)

        errors.concat(generated_header_errors(path))
      end

      Result.new(errors.uniq)
    end

    private

    attr_reader :repo, :base_sha, :head_sha

    def changed_paths
      repo.git("diff", "--name-status", "#{base_sha}...#{head_sha}").first.each_line.filter_map do |line|
        fields = line.strip.split("\t")
        fields.empty? ? nil : fields
      end
    end

    def blob_at(sha, path)
      return nil unless repo.git("cat-file", "-e", "#{sha}:#{path}", allow_failure: true).last.success?

      # Read (not GitRepository#file_at, which forces ASCII-8BIT) and
      # re-tag as UTF-8: this repo's managed files are UTF-8 text, and a
      # binary-tagged comparison against a UTF-8 sentinel literal silently
      # never matches instead of raising, which would fail this check open
      # rather than closed. Re-tagging (not transcoding) is exactly the
      # locale-independent fix issue #243 applies to the npm verifier.
      repo.git("show", "#{sha}:#{path}").first.dup.force_encoding(Encoding::UTF_8)
    end

    def sentinel_confinement_errors(path)
      head_text = blob_at(head_sha, path)
      return ["#{path} must still exist at the pull request head"] if head_text.nil?

      head_shape_errors = sentinel_shape_errors(path, head_text, "head")
      return head_shape_errors if head_shape_errors.any?

      base_text = blob_at(base_sha, path)
      if base_text.nil?
        return ["#{path} must already carry the managed contract sentinels at the pull request base " \
                "(first-time adoption is not eligible for this carve-out)"]
      end

      base_shape_errors = sentinel_shape_errors(path, base_text, "base")
      return base_shape_errors if base_shape_errors.any?

      return [] if outside_sentinel_span(base_text) == outside_sentinel_span(head_text)

      ["#{path} changed outside its managed sentinel span"]
    end

    def sentinel_shape_errors(path, text, side)
      begin_count = text.scan(SENTINEL_BEGIN).length
      end_count = text.scan(SENTINEL_END).length
      return ["#{path} is missing the managed contract sentinels at #{side}"] if begin_count.zero? || end_count.zero?
      return ["#{path} has duplicate managed contract sentinels at #{side}"] if begin_count > 1 || end_count > 1
      return ["#{path} sentinel order is inverted at #{side}"] if text.index(SENTINEL_BEGIN) > text.index(SENTINEL_END)

      []
    end

    def outside_sentinel_span(text)
      before, remainder = text.split(SENTINEL_BEGIN, 2)
      _inside, after = remainder.split(SENTINEL_END, 2)
      before + after
    end

    def generated_header_errors(path)
      head_text = blob_at(head_sha, path)
      return ["#{path} must still exist at the pull request head"] if head_text.nil?
      return ["#{path} must keep the generated-file header"] unless head_text.match?(GENERATED_FILE_HEADER)

      []
    end
  end
end
