# frozen_string_literal: true

module Verdify
  # Mechanically proves that a pull request's diff is confined to the
  # centrally-rendered agent-fleet CI/CD contract: the sentinel-delimited
  # span inside AGENTS.md/CLAUDE.md, the generated .agent-fleet/ci.yaml, and
  # the regenerated MANIFEST.sha256 -- and nothing else.
  #
  # This is the sole evidence a `verdify:fleet-contract-sync` labelled pull
  # request is judged against instead of the full lane-contract/critic
  # chain (jvallery/agents#3577, #3044). A pull request that carries the
  # label but changes anything outside this set, edits anything outside the
  # sentinel span, deletes a managed file, changes a managed file's type
  # (mode/symlink/gitlink), or duplicates/reorders/drops a sentinel fails
  # this check -- it is never silently downgraded to a weaker contract.
  #
  # This check bounds *where* a labelled pull request may write; it says
  # nothing about the semantic safety of *what* it writes there (the
  # sentinel span content and the .agent-fleet/ci.yaml command it declares
  # are not evaluated at all). Adding the managed paths to .github/CODEOWNERS
  # does NOT by itself require a human review before merge -- this repo's
  # dev branch runs required_approving_review_count: 0, and
  # require_code_owner_reviews only auto-requests an owner as a reviewer,
  # it does not block merging without their approval (proven by this repo's
  # own history: PRs #213/#230/#222 merged into dev touching CODEOWNERS-
  # protected paths with zero reviews). The actual human gate for this
  # route is scripts/delivery-gate.rb's own current-head APPROVED-review
  # requirement from a non-author allowed owner (mirroring what it already
  # requires for the dev -> main release route) -- see the fleet_contract_sync
  # branch there. This class has no opinion on review state; it only
  # answers the confinement question.
  class ManagedContractDiff
    SENTINEL_BEGIN = "<!-- BEGIN agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
    SENTINEL_END = "<!-- END agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
    SENTINEL_GUARDED_FILES = %w[AGENTS.md CLAUDE.md].freeze
    GENERATED_FILES = %w[.agent-fleet/ci.yaml].freeze
    MANIFEST_FILE = "MANIFEST.sha256"
    MANIFEST_LINE = /\A[0-9a-f]{64}  \S.*\z/.freeze
    GENERATED_FILE_HEADER = /\A# GENERATED by jvallery\/agents\b/.freeze
    REGULAR_FILE_MODE = "100644"
    ALLOWED_PATHS = (SENTINEL_GUARDED_FILES + GENERATED_FILES + [MANIFEST_FILE]).freeze

    Result = Struct.new(:errors) do
      def confined?
        errors.empty?
      end
    end

    def self.evaluate(repo:, base_sha:, head_sha:)
      new(repo: repo, base_sha: base_sha, head_sha: head_sha).evaluate
    end

    def initialize(repo:, base_sha:, head_sha:)
      @repo = repo
      @base_sha = base_sha
      @head_sha = head_sha
    end

    def evaluate
      errors = []
      changes = changed_paths
      if changes.empty?
        errors << "no changed paths to confirm as a managed contract sync"
        return Result.new(errors)
      end

      renamed = changes.select { |entry| entry.first.to_s.start_with?("R", "C") }
      if renamed.any?
        described = renamed.map { |entry| entry.drop(1).join(" -> ") }.sort.join(", ")
        errors << "renamed or copied paths are not permitted in a managed contract sync: #{described}"
      end

      ordinary = changes.reject { |entry| entry.first.to_s.start_with?("R", "C") }
      paths = ordinary.map { |entry| entry[1] }.uniq

      out_of_scope = paths - ALLOWED_PATHS
      errors << "changed paths outside the managed contract: #{out_of_scope.sort.join(', ')}" if out_of_scope.any?

      in_scope = ordinary.select { |entry| ALLOWED_PATHS.include?(entry[1]) }
      in_scope.each do |status, path|
        case status
        when "A", "M"
          errors.concat(mode_errors(path))
        when "D"
          errors << "managed contract paths must not be deleted: #{path}"
        else
          errors << "#{path} has an unsupported change type (#{status}); only add or modify is permitted for a managed contract sync"
        end
      end

      SENTINEL_GUARDED_FILES.each do |path|
        next unless paths.include?(path)

        errors.concat(sentinel_confinement_errors(path))
      end

      GENERATED_FILES.each do |path|
        next unless paths.include?(path)

        errors.concat(generated_header_errors(path))
      end

      errors.concat(manifest_shape_errors(MANIFEST_FILE)) if paths.include?(MANIFEST_FILE)

      Result.new(errors.uniq)
    end

    private

    attr_reader :repo, :base_sha, :head_sha

    # Parsed from `git diff --name-status -z`: NUL-terminated fields, never
    # string-split-and-stripped. Git's normal (non -z) path quoting only
    # escapes quotes, backslashes, control bytes, and non-ASCII -- a bare
    # trailing space is NOT quoted there, so a naive `line.strip.split`
    # parse silently eats a smuggled "AGENTS.md " into "AGENTS.md". `-z`
    # disables that quoting entirely and gives raw bytes; `core.quotePath
    # =false` is set defensively even though `-z` already implies it.
    def changed_paths
      # Force ASCII-8BIT before splitting: a path is not guaranteed to be
      # valid UTF-8 (a filesystem allows arbitrary bytes), and Open3's
      # default external encoding tags this output UTF-8 regardless. Given
      # invalid bytes, String#split on a UTF-8-tagged string raises
      # ArgumentError ("invalid byte sequence in UTF-8") before this method
      # even returns -- unlike the content-level checks below, there is no
      # later guard that could catch it. Splitting on a single-byte NUL
      # never needs character decoding, so ASCII-8BIT is always safe here;
      # the resulting path strings still compare correctly against the
      # ASCII-only ALLOWED_PATHS literals (Ruby treats an ASCII-only string
      # as encoding-compatible with any other encoding).
      output = repo.git("-c", "core.quotePath=false", "diff", "--name-status", "-z", "#{base_sha}...#{head_sha}").first.b
      tokens = output.split("\0")
      entries = []
      i = 0
      while i < tokens.length
        status = tokens[i]
        i += 1
        if status.start_with?("R", "C")
          entries << [status, tokens[i], tokens[i + 1]]
          i += 2
        else
          entries << [status, tokens[i]]
          i += 1
        end
      end
      entries
    end

    def blob_at(sha, path)
      return nil unless repo.git("cat-file", "-e", "#{sha}:#{path}", allow_failure: true).last.success?

      # Read (not GitRepository#file_at, which forces ASCII-8BIT) and
      # re-tag as UTF-8: this repo's managed files are UTF-8 text, and a
      # binary-tagged comparison against a UTF-8 sentinel literal silently
      # never matches instead of raising, which would fail this check open
      # rather than closed. Re-tagging (not transcoding) is exactly the
      # locale-independent fix issue #243 applies to the npm verifier.
      # valid_encoding? is checked explicitly by every caller before this
      # text is used in a String#scan/#split/#index -- those raise
      # ArgumentError (not Verdify::Error) on an invalid byte sequence,
      # which would otherwise propagate uncaught out of the CLI scripts.
      repo.git("show", "#{sha}:#{path}").first.dup.force_encoding(Encoding::UTF_8)
    end

    # `git ls-tree <sha> -- <path>` prints "<mode> <type> <blob-sha>\t<path>"
    # for a tracked path, or nothing (exit 0, empty stdout) if the path is
    # absent at that revision -- absence has to be read from empty output,
    # not a non-zero exit, unlike `cat-file -e`.
    def blob_mode(sha, path)
      output = repo.git("ls-tree", sha.to_s, "--", path).first
      line = output.each_line.first
      return nil if line.nil? || line.strip.empty?

      line.split(/\s+/, 2).first
    end

    # Confined-by-path is not confined-by-type: a managed path can be
    # replaced by a symlink, a gitlink (submodule entry), or simply have
    # its mode flipped to executable while its blob content is untouched --
    # none of that shows up as a content difference the sentinel/header/
    # manifest checks below would catch. Every allowed path must be a plain
    # regular file (mode 100644) at head, and at base too if it already
    # existed there.
    def mode_errors(path)
      errors = []
      head_mode = blob_mode(head_sha, path)
      if head_mode.nil?
        errors << "#{path} must be a regular tracked file at head"
      elsif head_mode != REGULAR_FILE_MODE
        errors << "#{path} must be a regular file (mode #{REGULAR_FILE_MODE}) at head, found mode #{head_mode}"
      end
      base_mode = blob_mode(base_sha, path)
      if base_mode && base_mode != REGULAR_FILE_MODE
        errors << "#{path} must be a regular file (mode #{REGULAR_FILE_MODE}) at base, found mode #{base_mode}"
      end
      errors
    end

    def sentinel_confinement_errors(path)
      head_text = blob_at(head_sha, path)
      return ["#{path} must still exist at the pull request head"] if head_text.nil?
      return ["#{path} is not valid UTF-8 at head"] unless head_text.valid_encoding?

      head_shape_errors = sentinel_shape_errors(path, head_text, "head")
      return head_shape_errors if head_shape_errors.any?

      base_text = blob_at(base_sha, path)
      if base_text.nil?
        return ["#{path} must already carry the managed contract sentinels at the pull request base " \
                "(first-time adoption is not eligible for this carve-out)"]
      end
      return ["#{path} is not valid UTF-8 at base"] unless base_text.valid_encoding?

      base_shape_errors = sentinel_shape_errors(path, base_text, "base")
      return base_shape_errors if base_shape_errors.any?

      return [] if outside_sentinel_span(base_text) == outside_sentinel_span(head_text)

      ["#{path} changed outside its managed sentinel span"]
    end

    def sentinel_shape_errors(path, text, side)
      begin_count = text.scan(SENTINEL_BEGIN).length
      end_count = text.scan(SENTINEL_END).length
      return ["#{path} is missing the managed contract sentinels at #{side}"] if begin_count.zero? || end_count.zero?
      return ["#{path} has duplicate managed contract sentinels at #{side}"] if begin_count > 1 || end_count > 1
      return ["#{path} sentinel order is inverted at #{side}"] if text.index(SENTINEL_BEGIN) > text.index(SENTINEL_END)

      []
    end

    def outside_sentinel_span(text)
      before, remainder = text.split(SENTINEL_BEGIN, 2)
      _inside, after = remainder.split(SENTINEL_END, 2)
      before + after
    end

    def generated_header_errors(path)
      head_text = blob_at(head_sha, path)
      return ["#{path} must still exist at the pull request head"] if head_text.nil?
      return ["#{path} is not valid UTF-8 at head"] unless head_text.valid_encoding?
      return ["#{path} must keep the generated-file header"] unless head_text.match?(GENERATED_FILE_HEADER)

      []
    end

    # MANIFEST.sha256 has no sentinel span and no header, so absent a shape
    # assertion it is a completely unchecked member of ALLOWED_PATHS:
    # `make manifest-check` only proves internal consistency with whatever
    # tree it is run against -- including a tree a confinement bypass has
    # already smuggled a path into -- it does not independently bound this
    # file's content. Require every non-blank line to look like a real
    # manifest entry (a 64-character hex digest, two spaces, a path) so a
    # mode-100644 binary/garbage replacement is still rejected.
    def manifest_shape_errors(path)
      head_text = blob_at(head_sha, path)
      return ["#{path} must still exist at the pull request head"] if head_text.nil?
      return ["#{path} is not valid UTF-8 at head"] unless head_text.valid_encoding?

      lines = head_text.each_line.map(&:chomp).reject(&:empty?)
      return ["#{path} must contain at least one manifest entry"] if lines.empty?

      malformed = lines.reject { |line| line.match?(MANIFEST_LINE) }
      return ["#{path} contains #{malformed.length} line(s) that are not a valid manifest entry"] if malformed.any?

      []
    end
  end
end
