#!/usr/bin/env ruby
# frozen_string_literal: true

require "minitest/autorun"
require "fileutils"
require "open3"
require "tmpdir"

require_relative "../lib/verdify"

class ManagedContractDiffTest < Minitest::Test
  BEGIN_SENTINEL = "<!-- BEGIN agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
  END_SENTINEL = "<!-- END agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"

  def git(dir, *args)
    stdout, stderr, status = Open3.capture3("git", "-C", dir, *args)
    raise "git #{args.join(' ')} failed: #{stderr}" unless status.success?

    stdout.strip
  end

  def write(dir, relative, content)
    path = File.join(dir, relative)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, content)
  end

  def commit_all(dir, message)
    git(dir, "add", "-A")
    git(dir, "commit", "-qm", message)
    git(dir, "rev-parse", "HEAD")
  end

  def agents_md(body)
    "# Repo\n\nSome repo-owned text before the contract.\n\n" \
      "#{BEGIN_SENTINEL}\n#{body}\n#{END_SENTINEL}\n\n" \
      "More repo-owned text after the contract.\n"
  end

  def ci_yaml(command)
    "# GENERATED by jvallery/agents from registry/repos/example.yaml ci_submission.\n" \
      "# Change the registry contract; do not hand-edit this managed file.\n" \
      "version: 1\nchecks:\n  steps:\n  - name: skills\n    command: #{command}\n"
  end

  # Baseline: AGENTS.md and CLAUDE.md already carry the sentinels (a repo
  # that has already adopted the contract once through the full lane), plus
  # an already-generated .agent-fleet/ci.yaml and a matching MANIFEST.sha256
  # placeholder. Returns [repo, dir, baseline_sha].
  def build_baseline
    dir = Dir.mktmpdir("managed-contract-diff-")
    git(dir, "init", "-q", "-b", "main")
    git(dir, "config", "user.name", "Verdify Test")
    git(dir, "config", "user.email", "verdify-test@example.invalid")
    write(dir, "AGENTS.md", agents_md("Old contract content v1."))
    write(dir, "CLAUDE.md", agents_md("Old contract content v1."))
    write(dir, ".agent-fleet/ci.yaml", ci_yaml("make test"))
    write(dir, "MANIFEST.sha256", "placeholder\n")
    write(dir, "scripts/unrelated.rb", "puts :unrelated\n")
    baseline = commit_all(dir, "baseline")
    [Verdify::GitRepository.new(dir), dir, baseline]
  end

  def evaluate(repo, base, head)
    Verdify::ManagedContractDiff.evaluate(repo: repo, base_sha: base, head_sha: head)
  end

  def test_confined_sentinel_edit_passes
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("New contract content v2."))
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "refresh contract")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a confined sentinel-only edit to pass: #{result.errors}"
  end

  def test_confined_generated_file_edit_passes
    repo, dir, base = build_baseline
    write(dir, ".agent-fleet/ci.yaml", ci_yaml("git diff --check && make test"))
    git(dir, "add", ".agent-fleet/ci.yaml")
    git(dir, "commit", "-qm", "refresh ci.yaml")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a confined ci.yaml edit to pass: #{result.errors}"
  end

  def test_manifest_only_change_passes
    repo, dir, base = build_baseline
    write(dir, "MANIFEST.sha256", "placeholder-updated\n")
    git(dir, "add", "MANIFEST.sha256")
    git(dir, "commit", "-qm", "regenerate manifest")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a MANIFEST.sha256-only change to pass: #{result.errors}"
  end

  def test_confined_multi_file_refresh_passes
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("New contract content v2."))
    write(dir, "CLAUDE.md", agents_md("New contract content v2."))
    write(dir, ".agent-fleet/ci.yaml", ci_yaml("git diff --check && make test"))
    write(dir, "MANIFEST.sha256", "placeholder-updated\n")
    git(dir, "add", "AGENTS.md", "CLAUDE.md", ".agent-fleet/ci.yaml", "MANIFEST.sha256")
    git(dir, "commit", "-qm", "full contract refresh")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a confined multi-file refresh to pass: #{result.errors}"
  end

  def test_out_of_scope_path_is_rejected
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("New contract content v2."))
    write(dir, "scripts/unrelated.rb", "puts :smuggled\n")
    git(dir, "add", "AGENTS.md", "scripts/unrelated.rb")
    git(dir, "commit", "-qm", "claims a refresh but smuggles a code change")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("changed paths outside the managed contract") && e.include?("scripts/unrelated.rb") },
           "expected rejection naming the out-of-scope path: #{result.errors}")
  end

  def test_edit_outside_sentinel_span_is_rejected
    repo, dir, base = build_baseline
    content = agents_md("Old contract content v1.").sub("Some repo-owned text before", "SMUGGLED repo-owned text before")
    write(dir, "AGENTS.md", content)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "edits outside the sentinel span")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md changed outside its managed sentinel span"
  end

  def test_duplicated_begin_sentinel_is_rejected
    repo, dir, base = build_baseline
    content = agents_md("Old contract content v1.").sub(BEGIN_SENTINEL, "#{BEGIN_SENTINEL}\n#{BEGIN_SENTINEL}")
    write(dir, "AGENTS.md", content)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "duplicates the begin sentinel")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md has duplicate managed contract sentinels at head"
  end

  def test_missing_end_sentinel_is_rejected
    repo, dir, base = build_baseline
    content = agents_md("Old contract content v1.").sub(END_SENTINEL, "")
    write(dir, "AGENTS.md", content)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "drops the end sentinel")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md is missing the managed contract sentinels at head"
  end

  def test_deleted_managed_file_is_rejected
    repo, dir, base = build_baseline
    FileUtils.rm(File.join(dir, "AGENTS.md"))
    git(dir, "add", "-A")
    git(dir, "commit", "-qm", "deletes the managed file")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("must not be deleted") || e.include?("must still exist") },
           "expected rejection of a deleted managed file: #{result.errors}")
  end

  def test_missing_generated_header_is_rejected
    repo, dir, base = build_baseline
    write(dir, ".agent-fleet/ci.yaml", "version: 1\nchecks:\n  steps:\n  - name: skills\n    command: make test\n")
    git(dir, "add", ".agent-fleet/ci.yaml")
    git(dir, "commit", "-qm", "drops the generated header")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, ".agent-fleet/ci.yaml must keep the generated-file header"
  end

  def test_first_time_adoption_without_prior_sentinels_is_not_eligible
    dir = Dir.mktmpdir("managed-contract-diff-adopt-")
    git(dir, "init", "-q", "-b", "main")
    git(dir, "config", "user.name", "Verdify Test")
    git(dir, "config", "user.email", "verdify-test@example.invalid")
    write(dir, "AGENTS.md", "# Repo\n\nNo managed contract yet.\n")
    base = commit_all(dir, "baseline without the contract")
    write(dir, "AGENTS.md", agents_md("First adoption."))
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "adopts the contract for the first time")
    head = git(dir, "rev-parse", "HEAD")
    repo = Verdify::GitRepository.new(dir)

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md is missing the managed contract sentinels at base"
  end

  def test_first_time_adoption_of_a_brand_new_file_is_not_eligible
    dir = Dir.mktmpdir("managed-contract-diff-new-file-")
    git(dir, "init", "-q", "-b", "main")
    git(dir, "config", "user.name", "Verdify Test")
    git(dir, "config", "user.email", "verdify-test@example.invalid")
    write(dir, "README.md", "# Repo\n")
    base = commit_all(dir, "baseline without an AGENTS.md at all")
    write(dir, "AGENTS.md", agents_md("First adoption."))
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "adds AGENTS.md for the first time")
    head = git(dir, "rev-parse", "HEAD")
    repo = Verdify::GitRepository.new(dir)

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("first-time adoption is not eligible for this carve-out") },
           "expected a brand-new managed file to be rejected: #{result.errors}")
  end

  def test_renamed_managed_file_is_rejected
    repo, dir, base = build_baseline
    git(dir, "mv", "AGENTS.md", "AGENTS.renamed.md")
    git(dir, "commit", "-qm", "renames the managed file")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("renamed or copied paths are not permitted") },
           "expected a rename to be rejected: #{result.errors}")
  end

  def test_no_changes_is_rejected
    repo, _dir, base = build_baseline

    result = evaluate(repo, base, base)
    refute result.confined?
    assert_includes result.errors, "no changed paths to confirm as a managed contract sync"
  end
end
